### ISSUE TITLE
Unable to reverse locate Singapore coordinates

### ISSUE THREAD

**Issue by LNSwamyJ** [joaquimserafim/node-open-geocoder#13]
Unable reverse locate below coordinates. I am able to find this coordinates in open street maps though.
1.279857 103.849335
undefined
Error: Invalid coordinates!
    at Geocoder.end (/data/data/com.termux/files/home/testnode/node_modules/node-open-geocoder/index.js:48:12)
    at getLocation (/data/data/com.termux/files/home/testnode/termuxapi.js:41:4)
    at /data/data/com.termux/files/home/testnode/termuxapi.js:24:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by LNSwamyJ** [comment]
Sorry about raising false alarm. I was parsing latitude and longitude in wrong order. Got it working after checking the index.js in node_module.
