### ISSUE TITLE
Not working anymore due to a redirection?

### ISSUE THREAD

**Issue by DigitalLeaves** [joaquimserafim/node-open-geocoder#6]
This module does not seem to be working anymore, probably due to a HTTPS redirection?
This is the output for the example in your Github README.md.
```
Error: Request Failed.
Status Code: 301
    at Geocoder.responseHandler (/path-to-project/node_modules/node-open-geocoder/index.js:98:13)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:539:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:444:20)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
```

I had a look at the code and actually it requests a http://... , but now nominatim.openstreetmap.org uses https and redirects from http to https.

**Comment by joaquimserafim** [comment]
will release a new version to fix this, thanks mate

**Comment by michelhn** [comment]
Anything new on this? I got the newest version and it's still the same

**Comment by joaquimserafim** [comment]
This issue should be fixed with **v3**
